### ISSUE TITLE
能在readme里稍微多些点文档说明吗？

### ISSUE THREAD

**Issue by willard-yuan** [wenzhixin/books#1]
你好，看了你这个豆瓣图书收藏夹，非常的有意思，你能在readme里稍微多些点文档说明吗？

**Comment by wenzhixin** [comment]
文档说明是指？

**Comment by willard-yuan** [comment]
因为我把它放在github page上后，发觉书籍信息无法显示，而我去看到代码的时候，没看见豆瓣的个人API。另外，`index.html`里载入的`css`和`js`链接路径也好像不对。我稍微修改了后，现在是这个样子：[demo](http://yongyuan.name/books/)

**Comment by wenzhixin** [comment]
是这样的，因为这里的图书都是我自己买的纸质书，然后通过豆瓣的 API 去获取数据，并没有真正使用豆瓣。https://github.com/wenzhixin/books/blob/master/data/data.js 这里根据书的 isbn 去更新书的列表信息。你是想显示你自己在豆瓣上收藏的书吧？那个倒是可以考虑改进下～

**Comment by willard-yuan** [comment]
`data.js`我没看见它在`index.html`里没看得见调用，囧。那如果我也要像你一样，只是抓取豆瓣的数据，我需要怎么做呢？

**Comment by wenzhixin** [comment]
因为我的书籍都是从 jd 和 amazon 上买的，所以 `chrome` 是谷歌浏览器的插件，专用于获取个人购买书籍的基本信息（标题和 ISBN），然后将数据保存成 `books.json`，再通过 `data.js` 通过豆瓣获取书籍的详细信息，最后界面上使用 `books.json` 的数据，并显示出来。

**Comment by willard-yuan** [comment]
嗯，思路明白了。我再看看，有问题还这里找你问哈。

**Comment by qingxp9** [comment]
很好的注意，我一般都是直接放豆瓣个人的地址，从作者博客上发现这样直接展示的效果挺不错。打算自己用Rails写个类似的。

**Comment by wenzhixin** [comment]
Good :)
